[[addons]]
zip = "https://github.com/hypernormalisation/SwedgeTimer/releases/download/2.0.8/SwedgeTimer-2.0.8-wrath.zip"

[[addons]]
git = "https://github.com/bkader/Dominos.git"

[[addons]]
git = "https://github.com/RichSteini/Bagnon-3.3.5.git"

[[addons]]
git = "https://github.com/TheNielDeal/GroupBulletinBoard.git"

[[addons]]
zip = "https://felbite.com/wp-content/uploads/2022/03/felbite.com-addoncontrolpanel-wotlk-addoncontrolpanel.zip"
