#[[addons]]
#zip = "https://github.com/hypernormalisation/SwedgeTimer/releases/download/2.0.8/SwedgeTimer-2.0.8-wrath.zip"

[[addons]]
git = "https://github.com/bkader/Dominos.git"

[[addons]]
git = "https://github.com/RichSteini/Bagnon-3.3.5.git"

[[addons]]
git = "https://github.com/TheNielDeal/GroupBulletinBoard.git"

[[addons]]
zip = "https://felbite.com/wp-content/uploads/2022/03/felbite.com-addoncontrolpanel-wotlk-addoncontrolpanel.zip"

[[addons]]
git = "https://github.com/Sattva-108/Leatrix_Plus.git"

[[addons]]
zip = "https://github.com/shagu/pfQuest/releases/latest/download/pfQuest-enUS-wotlk.zip"

[[addons]]
zip = "https://github.com/Bennylavaa/pfQuest-epoch/archive/master.zip"

[[addons]]
git = "https://github.com/NoM0Re/WeakAuras-WotLK.git"

#[[addons]]
#zip = "https://felbite.com/wp-content/uploads/2022/03/felbite.com-minimapbuttonframe-wotlk-minimapbuttonframe.zip"

[[addons]]
git = "https://github.com/Ascension-Addons/MoveAnything.git"
