[[addons]]
url = "https://github.com/bkader/Dominos.git"

[[addons]]
url = "https://github.com/RichSteini/Bagnon-3.3.5.git"

[[addons]]
url = "https://github.com/Bennylavaa/LFG.git"

[[addons]]
url = "https://felbite.com/wp-content/uploads/2022/03/felbite.com-addoncontrolpanel-wotlk-addoncontrolpanel.zip"

[[addons]]
url = "https://github.com/Sattva-108/Leatrix_Plus.git"

[[addons]]
url = "https://github.com/shagu/pfQuest/releases/latest/download/pfQuest-enUS-wotlk.zip"

[[addons]]
url = "https://github.com/Bennylavaa/pfQuest-epoch/archive/master.zip"

[[addons]]
url = "https://github.com/NoM0Re/WeakAuras-WotLK.git"

[[addons]]
url = "https://felbite.com/wp-content/uploads/2022/03/felbite.com-moveanything-wotlk-moveanything.zip"

[[addons]]
url = "https://github.com/RichSteini/NotPlater.git"

[[addons]]
url = "https://gitlab.com/Tsoukie/compactraidframe-3.3.5.git"

[[addons]]
url = "https://gitlab.com/Tsoukie/compactraidframe_healex.git"

[[addons]]
url = "https://gitlab.com/Tsoukie/enhancedraidframes-3.3.5.git"

[[addons]]
url = "https://gitlab.com/Tsoukie/classicapi.git"

[[addons]]
url = "https://github.com/alchem1ster/WotLK-Auctionator.git"

[[addons]]
url = "https://felbite.com/wp-content/uploads/2022/03/felbite.com-omnicc-wotlk-omnicc.zip"

[[addons]]
url = "https://github.com/Carnivohra/NugEnergy.git"

[[addons]]
url = "https://github.com/Raynbock/AtlaslootProjectEpoch.git"

[[addons]]
url = "https://github.com/gareth-charles/Quartz.git"

[[addons]]
url = "https://warperia.com/wp-content/uploads/2024/12/wotlk-prat-011224.zip"

[[addons]]
url = "https://github.com/Bunny67/Details-WotLK.git"

[[addons]]
url = "https://felbite.com/wp-content/uploads/2022/03/felbite.com-align-wotlk-align.zip"

[[addons]]
url = "https://github.com/fondlez/GroupBulletinBoard.git"

[[addons]]
url = "https://github.com/NeticSoul/DragonUI.git"

[[addons]]
url = "https://github.com/SimonGaufreteau/ZygorGuidesViewer.git"
